########################## Filebeat Configuration ###########################
filebeat.max_start_delay: 10s
name: ${NODE_NAME}
setup.dashboards.enabled: true
setup.template.enabled: true
setup.kibana:
  host: "kibana:5601"

filebeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              docker.container.image: mongo
          config:
            - module: mongodb
              log:
                input:
                  type: docker
                  containers.ids:
                    - "${data.docker.container.id}"

    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              docker.container.image: apache
          config:
            - module: apache
              access:
                input:
                  type: docker
                  containers.ids:
                    - ${data.docker.container.id}
              error:
                input:
                  type: docker
                  containers.ids:
                    - ${data.docker.container.id}

    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              docker.container.image: haproxy
          config:
            - module: haproxy
              log:
                input:
                  type: docker
                  containers.ids:
                    - "${data.docker.container.id}"

filebeat.modules:
- module: system
  syslog:
    enabled: true
  auth:
    enabled: true
- module: postgresql
  log:
    enabled: true

filebeat.inputs:
- type: docker
  combine_partial: true
  containers:
    path: "/var/lib/docker/containers"
    ids:
      - "*"
  json.keys_under_root: true
  json.add_error_key: false
  json.ignore_decoding_error: true

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

output:
   elasticsearch: 
     hosts: ["http://elasticsearch:9200"]

logging.level: info
logging.json: true
logging.metrics.enabled: false
ssl.verification_mode: none
